### ISSUE TITLE
This project not work

### ISSUE THREAD

**Issue by ghost** [auraphp/system#37]
This is a result of command `composer create-project aura/system my-project`

![Schermata del 2019-06-20 15-35-25](https://user-images.githubusercontent.com/14064365/59853408-1ab27000-9371-11e9-8ed9-5cd2ad635ea6.png)

In any case, it uses too many dependencies (psr and monolog but unfortunately I noticed zend dependencies too)

Too bad ... it could be nice to do something simple.

**Comment by koriym** [comment]
It is not a package issue but a problem with your environment? (downloading failure)
There was no problem as follows.

```
$ composer create-project aura/system aura
Installing aura/system (1.0.1)
  - Installing aura/system (1.0.1): Downloading (100%)         
Created project in sys
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 18 installs, 0 updates, 0 removals
  - Installing aura/installer-system (1.0.2): Downloading (100%)         
  - Installing aura/autoload (1.x-dev e202795): Cloning e202795c61 from cache
  - Installing aura/cli (1.x-dev 54ff125): Cloning 54ff125e36 from cache
  - Installing aura/di (1.x-dev b2a0479): Cloning b2a0479ead from cache
  - Installing aura/filter (1.x-dev 5d04999): Cloning 5d0499988f from cache
  - Installing aura/http (1.x-dev 3734111): Cloning 3734111441 from cache
  - Installing aura/input (1.x-dev e980570): Cloning e980570828 from cache
  - Installing aura/intl (1.x-dev 1ae41d5): Cloning 1ae41d569a from cache
  - Installing aura/marshal (1.x-dev a41dada): Cloning a41dada480 from cache
  - Installing aura/router (1.x-dev d78ce7c): Cloning d78ce7c4a4 from cache
  - Installing aura/session (1.x-dev 009193c): Cloning 009193c405 from cache
  - Installing aura/signal (1.x-dev e617033): Cloning e6170331ba from cache
  - Installing aura/sql (1.x-dev 56bf2f9): Cloning 56bf2f9066 from cache
  - Installing aura/uri (1.x-dev e3b4ae3): Cloning e3b4ae381d from cache
  - Installing aura/view (1.x-dev 5b46eaa): Cloning 5b46eaa5e8 from cache
  - Installing aura/web (1.x-dev 28dce9c): Cloning 28dce9c1d0 from cache
  - Installing aura/framework (dev-develop 80358eb): Cloning 80358eb9d2 from cache
  - Installing aura/framework-demo (1.0.1): Downloading (100%)         
Writing lock file
Generating autoload files
```

**Comment by harikt** [comment]
To add : Also this is 1.x version which is no longer supported ?. If you are looking to try 2.x , here it is  https://github.com/auraphp/Aura.Web_Project .

**Comment by koriym** [comment]
@harikt Shouldn't we identify which package is deprecated?

**Comment by harikt** [comment]
1.x packages are deprecated. Don't know what should we do if we deprecate those and how to let people know it is deprecated. If you have some ideas I am open for it.

**Comment by koriym** [comment]
@harikt What about to indicate in "topic"? 
 
![image](https://user-images.githubusercontent.com/529021/59902432-22d5e280-9439-11e9-92ca-bef363dd3fb3.png)

See my case. (+description)
https://github.com/koriym/Koriym.FakeJsons

**Comment by koriym** [comment]
Found the article about it. They also suggest using the topic.
https://medium.com/maintainer-io/how-to-deprecate-a-repository-on-github-8f0ceb9155e

Also, we can abandon the package in packagist. (They provide "Abandon" button)
https://stackoverflow.com/questions/40946151/marking-a-packagist-package-as-abandoned-in-favor-of-a-new-location

**Comment by harikt** [comment]
Added deprecated tag for this repo.
